services:
  streamlit:
    image: rdinit/redlabhack:streamlit
    ports:
     - "8501:8501"
    restart: unless-stopped
    networks:
     - internal
     - web
    labels:
     - traefik.enable=true
     - traefik.http.routers.streamlit.rule=Host(`prezoy.itatmisis.ru`)
     - traefik.http.routers.streamlit.entrypoints=websecure, web
     - traefik.http.routers.streamlit.tls=true
     - traefik.http.routers.streamlit.tls.certresolver=le
     - traefik.http.services.streamlit.loadbalancer.server.port=8501
     - traefik.docker.network=web  

  api:
    image: rdinit/redlabhack:api
    ports:
     - "8000:8000"
    depends_on:
     - kafka
    restart: unless-stopped
    networks:
     - internal
     - web
    labels:
     - traefik.enable=true
     - traefik.http.routers.api.rule=Host(`prezoy.itatmisis.ru`) && PathPrefix(`/api`)
     - traefik.http.middlewares.api.stripprefix.prefixes=/api"
     - traefik.http.routers.api.entrypoints=websecure, web
     - traefik.http.routers.api.tls=true
     - traefik.http.routers.api.tls.certresolver=le
     - traefik.http.services.api.loadbalancer.server.port=8000
     - traefik.docker.network=web   
     

  ml1:
    image: rdinit/redlabhack:ml1
    depends_on:
     - kafka
    restart: unless-stopped

  ml2:
    image: rdinit/redlabhack:ml2
    depends_on:
     - kafka
    restart: unless-stopped

  ml3:
    image: rdinit/redlabhack:ml3
    depends_on:
     - kafka
    restart: unless-stopped
    

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
    #ports:
    #  - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
     - zookeeper
    #ports:
    #  - 29092:29092
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 100001200

networks:
  web:
    external: true
  internal:
    external: false